# Generated by Django 5.0.7 on 2024-07-23 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyDjango_App', '0002_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
